version: "3"
services:
  app:
    container_name: sbib-app
    restart: always
    build: .
    ports:
      - "9494:9494"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    env_file:
      - .env
  db:
    image: mysql
    container_name: sbib-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
        - .env
    ports:
      - "3306:3306"
    volumes:
      - 'sbib-data:/var/lib/mysql'

volumes: 
  sbib-data: 