version: "3"
services:
  api:
    container_name: sbib-api
    restart: always
    build: .
    ports:
      - "9494:9494"
      - "9495:80"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    env_file:
      - .env
  db:
    image: mysql
    container_name: sbib-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"