version: "3"
services:
    app:
        image: sbnpsi/sbib_app:production
        container_name: sbib-app
        restart: always
        ports:
          - "4200:80"
        environment:
          - NODE_ENV=production
    api:
        image: sbnpsi/sbib_api:production
        container_name: sbib-api
        restart: always
        ports:
            - "9494:9494"
        depends_on:
            - db
        environment:
            - NODE_ENV=production
        env_file:
            - .env
    db:
        image: mysql
        container_name: sbib-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        ports:
            - "3306:3306"