import {MigrationInterface, QueryRunner} from "typeorm";

export class FootprintImageId1632172720774 implements MigrationInterface {
    name = 'FootprintImageId1632172720774'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `footprints` CHANGE `imageName` `imageId` varchar(255) NULL");
        await queryRunner.query("CREATE TABLE `places` (`id` int NOT NULL AUTO_INCREMENT, `Name` varchar(255) NOT NULL, `Target` varchar(255) NOT NULL, `Diameter` double NOT NULL, `centerlat` double NOT NULL, `centerlon` double NOT NULL, `CoordinateSys` varchar(255) NOT NULL, `Approval` varchar(255) NOT NULL, `Origin` varchar(255) NOT NULL, `ApprovalDate` date NOT NULL, `targetId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `comment`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `date`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `fc`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `name`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `note`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `status`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `version`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `vir`");
        await queryRunner.query("ALTER TABLE `seqs` DROP COLUMN `target_id`");
        await queryRunner.query("ALTER TABLE `targets` ADD `Name` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `Version` int NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `Date` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `FC` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `VIR` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `Note` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `Status` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `Comment` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `seqs` ADD `targetId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `image_name` `image_name` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `is_done` `is_done` tinyint NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `time` `time` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `instrument` `instrument` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `thumb` `thumb` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `exposure` `exposure` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `target_name` `target_name` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `target_desc` `target_desc` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `min_lat` `min_lat` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `max_lat` `max_lat` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `min_lon` `min_lon` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `max_lon` `max_lon` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `seq_id` `seq_id` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `min_res` `min_res` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `central_body` `central_body` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `obs_type` `obs_type` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `mission_phase` `mission_phase` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `sequence_id` `sequence_id` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `sequence_title` `sequence_title` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `i_spice` `i_spice` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `t_spice` `t_spice` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `cal_flat` `cal_flat` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `samples` `samples` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `lines` `lines` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `footprint` `footprint` text NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `filter` `filter` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `shape` `shape` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `level` `level` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `f_lines` `f_lines` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `f_samples` `f_samples` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `projection` `projection` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `version` `version` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `orbit` `orbit` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `nadir` `nadir` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `filename` `filename` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `filename_a` `filename_a` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `i` `i` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `e` `e` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `phase` `phase` int NOT NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `softVers` `softVers` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `footprints` DROP COLUMN `imageId`");
        await queryRunner.query("ALTER TABLE `footprints` ADD `imageId` int NULL");
        await queryRunner.query("ALTER TABLE `targets` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `targets` ADD `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `targets` CHANGE `model_path` `model_path` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` CHANGE `material_path` `material_path` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` CHANGE `image_basepath` `image_basepath` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `id` `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `seqs` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `seqs` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `seqs` ADD `id` int NOT NULL PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `name` `name` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `use_me` `use_me` tinyint NOT NULL");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `is_useme` `is_useme` tinyint NOT NULL");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `is_done` `is_done` tinyint NOT NULL");
        await queryRunner.query("ALTER TABLE `footprints` ADD CONSTRAINT `FK_152a4379f6b438b62b7a4dc4ed6` FOREIGN KEY (`imageId`) REFERENCES `images`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `places` ADD CONSTRAINT `FK_4a99381d32efde695f86dd0e70c` FOREIGN KEY (`targetId`) REFERENCES `targets`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `places` DROP FOREIGN KEY `FK_4a99381d32efde695f86dd0e70c`");
        await queryRunner.query("ALTER TABLE `footprints` DROP FOREIGN KEY `FK_152a4379f6b438b62b7a4dc4ed6`");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `is_done` `is_done` tinyint(1) NULL");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `is_useme` `is_useme` tinyint(1) NULL");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `use_me` `use_me` tinyint NULL");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `name` `name` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `seqs` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `seqs` ADD `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `seqs` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `seqs` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT");
        await queryRunner.query("ALTER TABLE `targets` CHANGE `image_basepath` `image_basepath` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` CHANGE `material_path` `material_path` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` CHANGE `model_path` `model_path` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `id`");
        await queryRunner.query("ALTER TABLE `targets` ADD `id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD PRIMARY KEY (`id`)");
        await queryRunner.query("ALTER TABLE `footprints` DROP COLUMN `imageId`");
        await queryRunner.query("ALTER TABLE `footprints` ADD `imageId` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `softVers` `softVers` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `phase` `phase` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `e` `e` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `i` `i` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `filename_a` `filename_a` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `filename` `filename` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `nadir` `nadir` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `orbit` `orbit` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `version` `version` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `projection` `projection` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `f_samples` `f_samples` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `f_lines` `f_lines` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `level` `level` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `shape` `shape` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `filter` `filter` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `footprint` `footprint` text NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `lines` `lines` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `samples` `samples` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `cal_flat` `cal_flat` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `t_spice` `t_spice` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `i_spice` `i_spice` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `sequence_title` `sequence_title` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `sequence_id` `sequence_id` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `mission_phase` `mission_phase` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `obs_type` `obs_type` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `central_body` `central_body` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `min_res` `min_res` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `seq_id` `seq_id` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `max_lon` `max_lon` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `min_lon` `min_lon` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `max_lat` `max_lat` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `min_lat` `min_lat` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `target_desc` `target_desc` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `target_name` `target_name` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `exposure` `exposure` int NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `thumb` `thumb` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `instrument` `instrument` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `time` `time` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `is_done` `is_done` tinyint NULL");
        await queryRunner.query("ALTER TABLE `images` CHANGE `image_name` `image_name` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `seqs` DROP COLUMN `targetId`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `Comment`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `Status`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `Note`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `VIR`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `FC`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `Date`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `Version`");
        await queryRunner.query("ALTER TABLE `targets` DROP COLUMN `Name`");
        await queryRunner.query("ALTER TABLE `seqs` ADD `target_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `vir` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `version` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `status` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `note` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `name` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `fc` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `date` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `targets` ADD `comment` varchar(255) NULL");
        await queryRunner.query("DROP TABLE `places`");
        await queryRunner.query("ALTER TABLE `footprints` CHANGE `imageId` `imageName` varchar(255) NULL");
    }

}
